---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории 1
  - Пользователь должен иметь возможность фильтровать товары 2
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре 3
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины 4
  - На странице товара и в каталоге должно выводиться название, рейтинг, цена со скидкой и без нее 5
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжить выбирать товары в каталоге 6
  - На странице корзины пользователь должен иметь возможность удалять товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты 7
  - Корзина должна храниться в сессии браузера 8
  - Сайт должен будет SPA-приложение, которое не перезагружает страницу 9
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы 10
  - Сайт должен быть безопасным и защищать данные пользователя 11
  - Сайт должен иметь мобильную версию 12
  - Сайт нужно протестировать на совместимость с последними версиями браузеров 13
  - Важно, чтобы сайт мог обрабатывать большое количество трафика 14
  - Сайт должен быть доступен на различных устройствах 15
implicit:
  - Сайт должен выдерживать нагрузку в 1000 пользователей 16
  - Платежная система должна выдерживать 500 запросов в секунду 17
  - Пользователь не может редактировать описание товара 18
